on:
  push:
    branches:
      - main
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-node@v2
      - name: install dependencies
        run: npm ci
      - run: npm test


